"""add violations table

Revision ID: 11d4897e0246
Revises: d18996265a5d
Create Date: 2024-12-10 14:23:30.164295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d4897e0246'
down_revision = 'd18996265a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currently_in_litigation', sa.Boolean(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords_table.id'], name=op.f('fk_violations_table_landlord_id_landlords_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.drop_column('currently_in_litigation')
        batch_op.drop_column('something_new')
        batch_op.drop_column('violations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('violations', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('something_new', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('currently_in_litigation', sa.BOOLEAN(), nullable=True))

    op.drop_table('violations_table')
    # ### end Alembic commands ###
