"""add tenants

Revision ID: 81f058c41cd3
Revises: 11d4897e0246
Create Date: 2024-12-10 15:56:39.292104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f058c41cd3'
down_revision = '11d4897e0246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_violations_table_tenant_id_tenants_table'), 'tenants_table', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_violations_table_tenant_id_tenants_table'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('tenants_table')
    # ### end Alembic commands ###
