"""add rating to landlord

Revision ID: 846851e1d86d
Revises: 81f058c41cd3
Create Date: 2024-12-11 13:25:58.456153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846851e1d86d'
down_revision = '81f058c41cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
