"""add something_new column

Revision ID: d18996265a5d
Revises: cfaef8be69e3
Create Date: 2024-12-10 14:05:58.035621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18996265a5d'
down_revision = 'cfaef8be69e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('something_new', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords_table', schema=None) as batch_op:
        batch_op.drop_column('something_new')

    # ### end Alembic commands ###
